dist: bionic
language: python
python: 3.6
env:
  global
    - SECRET_KEY="(&^+4@&qt4b-^1=mad05%ju8q+4vg(vy6r2mq+gxab2eg#0f$b"
    - DJANGO_SETTINGS_MODULE=config.settings.testing
    - ENVIRONMENT=TESTING
    - ADMIN_EMAIL="admin@test.email"
    - ADMIN_PHONE_NUMBER=0911427805
    - ADMIN_PASSWORD=""
    - ADMIN_FIRST_NAME=admin
    - ADMIN_LAST_NAME=user
    - DB_NAME=travis_ci_test
    - DB_ROOT_PASSWORD=""
    - DB_USER=travis
    - DB_PASSWORD=""
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - CELERY_BROKER_URL=redis://127.0.0.1:6379
    - CELERY_RESULT_BACKEND=redis://127.0.0.1:6379
    - PIPENV_IGNORE_VIRTUALENVS=1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;'
install:
  - pip3 install --upgrade pip
  - pip3 install pipenv
  - pipenv install --system
before_script:
  - python manage.py migrate --no-input
  - python manage.py runfixtures
script:
  - python manage.py test --verbosity 2
